language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - if [ $(phpenv version-name) != "5.6" ]; then vendor/bin/phpunit; fi
  - if [ $(phpenv version-name)  == "5.6" ]; then vendor/bin/phpunit --coverage-clover=build/coverage.clover; fi

after_script:
  - if [ $(phpenv version-name) == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $(phpenv version-name) == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.clover; fi
